name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: debian:11

    steps:
    - name: Install deps
      run: apt update && apt install -y aria2 wget unzip build-essential cmake lsb-release software-properties-common gnupg git

    - name: Install LLVM
      run: bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
    
    - name: Set up Android NDK r23b
      run: | 
        aria2c -o android-ndk-r23b-linux.zip https://dl.google.com/android/repository/android-ndk-r23b-linux.zip
        unzip -q -d ~ android-ndk-r23b-linux.zip
      
    - uses: actions/checkout@v4

    - name: Build
      run: |
        git config --global --add safe.directory /__w/wrapper/wrapper
        mkdir build
        cd build
        cmake ..
        make

    - name: Set outputs
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Wrapper.x86_64.${{ steps.vars.outputs.sha_short }}
        include-hidden-files: true
        path: |
          rootfs
          wrapper
          Dockerfile
        

